# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(852, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.kSlider = QtWidgets.QSlider(self.centralwidget)
        self.kSlider.setGeometry(QtCore.QRect(80, 190, 160, 22))
        self.kSlider.setMinimum(2)
        self.kSlider.setMaximum(5)
        self.kSlider.setProperty("value", 2)
        self.kSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kSlider.setObjectName("kSlider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 90, 47, 16))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.archivoBuscado = QtWidgets.QLineEdit(self.centralwidget)
        self.archivoBuscado.setGeometry(QtCore.QRect(130, 90, 351, 20))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(9)
        self.archivoBuscado.setFont(font)
        self.archivoBuscado.setReadOnly(True)
        self.archivoBuscado.setObjectName("archivoBuscado")
        self.botonBuscarArchivo = QtWidgets.QPushButton(self.centralwidget)
        self.botonBuscarArchivo.setGeometry(QtCore.QRect(500, 90, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.botonBuscarArchivo.setFont(font)
        self.botonBuscarArchivo.setObjectName("botonBuscarArchivo")
        self.valoresK = QtWidgets.QLabel(self.centralwidget)
        self.valoresK.setGeometry(QtCore.QRect(80, 140, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.valoresK.setFont(font)
        self.valoresK.setObjectName("valoresK")
        self.botonAleatorio = QtWidgets.QPushButton(self.centralwidget)
        self.botonAleatorio.setGeometry(QtCore.QRect(80, 270, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.botonAleatorio.setFont(font)
        self.botonAleatorio.setObjectName("botonAleatorio")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 240, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.botonHeuristica = QtWidgets.QPushButton(self.centralwidget)
        self.botonHeuristica.setGeometry(QtCore.QRect(210, 270, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.botonHeuristica.setFont(font)
        self.botonHeuristica.setObjectName("botonHeuristica")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 190, 171, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold Condensed")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.vistaResultados = QtWidgets.QListView(self.centralwidget)
        self.vistaResultados.setGeometry(QtCore.QRect(460, 220, 321, 271))
        self.vistaResultados.setObjectName("vistaResultados")
        """ MainWindow.setCentralWidget(self.centralwidget) """
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        """ MainWindow.setStatusBar(self.statusbar) """

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Trabajo Práctico Final - Inteligencia Artifical 2 - Kmeans -Gomez-Perez-Romero"))
        self.label.setText(_translate("MainWindow", "Archivo:"))
        self.botonBuscarArchivo.setText(_translate("MainWindow", "Buscar"))
        self.valoresK.setText(_translate("MainWindow", "Cantidad de clusters: 2"))
        self.botonAleatorio.setText(_translate("MainWindow", "Aleatoria"))
        self.label_3.setText(_translate("MainWindow", "Inicialización de los clusters:"))
        self.botonHeuristica.setText(_translate("MainWindow", "Heurística"))
        self.label_4.setText(_translate("MainWindow", "Resultados de la última ejecución"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
